model_list:
  - model_name: gpt-3.5-turbo # gemini-pro
    litellm_params:
      model: gemini/gemini-pro
  # - model_name: gpt-3.5-turbo # claude-3-sonnet
  #   litellm_params:
  #     model: claude-3-sonnet-20240229

litellm_settings:
  drop_params: True
