model_list:
  - model_name: gpt-3.5-turbo # bedrock(claude3-sonnet)
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
  - model_name: gpt-3.5-turbo # gemini-pro
    litellm_params:
      model: gemini/gemini-pro
  # - model_name: gpt-3.5-turbo # claude3-sonnet
  #   litellm_params:
  #     model: claude-3-sonnet-20240229
  - model_name: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0

litellm_settings:
  drop_params: True
